### ISSUE TITLE
HK 10646 JPTableFull.pdf

### ISSUE THREAD

**Issue by nathanhammond** [unicode-org/unihan-database#1]
I've been working on pronunciations and readings of characters over at [cantonese/parse-jyutping-table-full](https://github.com/cantonese/parse-jyutping-table-full) which pulls from Hong Kong's submission to ISO 10646.

I'm aware that you're familiar with [JPTableFull.pdf](https://www.iso10646hk.net/download/jp/doc/JPTableFull.pdf); [I've seen your proposal regarding `kCantonese`](https://www.unicode.org/L2/L2020/20153-kcantonese-field.pdf). In that proposal you state "We note that the Hong Kong governments data is encumbered by a license which prevents our using it directly." I'm wondering where you're sourcing your licensing information.

[From the OGCIO](https://www.ogcio.gov.hk/tc/our_work/business/tech_promotion/ccli/cliac/canton_pronun_list.html) the statement is "免費供市民參考及使用。" which could be roughly translated as "free of charge, for citizens' reference and use." or "freely offered, for citizens' reference and use." This reads to me approximately as a dedication to the public domain hinging on "市民" and retransmittability.

My reading of the statement on the [root page of the iso10646hk.net site](https://www.iso10646hk.net/jp/index.jsp):

> Information provided on this website is for education and promotion of Cantonese Pin Yin (Jyut Ping). Permission is given to all non-profit or education organizations for hyperlink provision to this site without the need for written consent.

... is that it applies to the remainder of the site, separate from the submission to ISO 10646.

I've reached out to the OGCIO for further clarification. You can keep track of that response at https://github.com/cantonese/parse-jyutping-table-full/issues/1

**Comment by kenlunde** [comment]
I see that you are not getting any response from OGCIO, so I will go ahead and close this issue.
